### ISSUE TITLE
check return value of `File.Close()`

### ISSUE THREAD

**Issue by mark-kubacki** [zupzup/golang-http-file-upload-download#2]
It's admittedly a common mistake to forget it, `File.Close()` can and sometimes does [return an error](https://github.com/golang/go/blob/go1.9/src/os/file_unix.go#L189:16), too, which needs to be handled. (`Close()` is *idempotent*, you can call it multiple times.)

As next step you will need to check if a file has been created (despite the error), and if so then remove it.

(Or more elegantly, create with Linux' `O_TMPFILE`. See my [caddy.upload](https://github.com/wmark/caddy.upload/blob/4d67e983b3908041cf17971e77552ab147fe85b2/protofile/otmpfile_linux.go#L29-L86).)

**Comment by zupzup** [comment]
Thank you for the suggestion. I'm aware of this, but left it out for brevity in this example. 😅 

I agree however, this being an educational repository / blog post, that it should be in there. I'll add it over the holidays. :)

**Comment by mark-kubacki** [comment]
Any free time to tackle this? I could file a PR if you want.

**Comment by zupzup** [comment]
Hey, sorry, I completely forgot about this. 🙈 

I'd very much appreciate a PR!
