### ISSUE TITLE
我在使用postman上传文件的时候，为什么会报错

### ISSUE THREAD

**Issue by Smityz** [zupzup/golang-http-file-upload-download#5]
file, _, err := r.FormFile("uploadFile")
在这一句中，err爆出异常http: no such file
然后我回头输出了一下r.Body的大小,发现是0
请问这是怎么回事呢
![image](https://user-images.githubusercontent.com/22953824/56195013-aaccf400-6066-11e9-9979-c95ed1869a29.png)
这是我postman的参数

**Comment by zupzup** [comment]
hey :) I'm sorry, but I can't read any of that 😅 Could you please provide your question/issue in english?

**Comment by Smityz** [comment]
I am sorry for that,because I got this repositories from a Chinese website,and I missed it was a translated article.
When I use Postman to upload my file,there is an error throwed by
”file, _, err := r.FormFile("uploadFile")“
And the error is http: no such file
Then I checked the r.Body,it was 0
There is my postman setting
![image](https://user-images.githubusercontent.com/22953824/56195743-1fecf900-6068-11e9-946f-9701d3ed7b8a.png)
What's wrong with it?

**Comment by zupzup** [comment]
I believe you need to set the `key` of the file to `uploadFile`.

Like this:

![Screenshot 2019-04-16 at 11 03 14](https://user-images.githubusercontent.com/942652/56196526-48a8ca80-6037-11e9-81aa-219fe7723029.png)

**Comment by Smityz** [comment]
Yes,you are right thx :}

**Comment by Smityz** [comment]
And there is another problem is,when I upload a file,it always CANT_READ_FILE_TYPE
![image](https://user-images.githubusercontent.com/22953824/56219521-77f02380-6099-11e9-96d9-378ddfff6537.png)
![image](https://user-images.githubusercontent.com/22953824/56219531-7c1c4100-6099-11e9-8357-352a10741d59.png)
Sorry,i am a rookie

**Comment by zupzup** [comment]
Strange. Does this happen with all files? Maybe the file is actually a png and renamed to jpg, or vice versa?

**Comment by Smityz** [comment]
when I rename a png to jpg,the filetype is changed too.I don't know why...

**Comment by Smityz** [comment]
![1231231](https://user-images.githubusercontent.com/22953824/56223571-99084280-60a0-11e9-98bb-a5e94ab0e4df.jpg)
here is my test picture

**Comment by zupzup** [comment]
Ah, there is an error in the code i think - 

If you change 
```go
	fileEndings, err := mime.ExtensionsByType(fileType)
```
TO
```go
	fileEndings, err := mime.ExtensionsByType(filetype)
```
Does it work?

Or you can specify a `type` form value, with the correct file type. But the above should work as well. There are 2 variables named `fileType` and `filetype` and I think it's using the wrong one.

**Comment by Smityz** [comment]
I will find another way to achieve this function,if I find it I will tell you.
thank you very much
best wishes

**Comment by mrostamii** [comment]
Hi.

I have the same issue on the Postman. At first, the problem occurred because of `uploadFile` key then it has occurred because of the first `CANT_WRITE_FILE` statement:  

```
defer newFile.Close()
		if _, err := newFile.Write(fileBytes); err != nil || newFile.Close() != nil {
			renderError(w, "CANT_WRITE_FILE2", http.StatusInternalServerError)
			return
		}
```  

Any suggestion?
