### ISSUE TITLE
Get CANT_WRITE_FILE error when I upload a file using Postman

### ISSUE THREAD

**Issue by mrostamii** [zupzup/golang-http-file-upload-download#7]
Hi.

I have [the same](https://github.com/zupzup/golang-http-file-upload-download/issues/5) issue on the Postman. At first, the problem occurred because of `uploadFile` key then it has occurred because of the first `CANT_WRITE_FILE` statement:  

```
defer newFile.Close()
		if _, err := newFile.Write(fileBytes); err != nil || newFile.Close() != nil {
			renderError(w, "CANT_WRITE_FILE2", http.StatusInternalServerError)
			return
		}
```  

Any suggestion?

**Comment by zupzup** [comment]
Hey,

you could try logging the error that happens. If I could guess, I'd say it's a permissions error (your server is not allowed to write at the path)

**Comment by mrostamii** [comment]
After I POST a `.png` file, it got a log but the error still there: 

    FileType: image/png, File: tmp/521fc4ab617ede2508619776.png

I'm sure that I got the access (`777`) to the file on the server (Ubuntu 18.04).

The file named `982.png` but as you see on the log they're not the same. Does it happen because of ` tmp/` that is not located/created on the server?

**Comment by zupzup** [comment]
What if you log the error that happens here:

```go
if _, err := newFile.Write(fileBytes); err != nil || newFile.Close() != nil {
  // log error here
}
```

Because this is the error, which triggers the `CANT_WRITE_FILE`. Depending on what that error is, you'll likely be able to fix the issue

**Comment by mrostamii** [comment]
Ah, problem solved. 

**Solution:** 
I created a `tmp` directory and then the picture has saved there. Also, I got `SUCCESS` message after that.

Thank you.
