### ISSUE TITLE
Fix maxUploadSize in article

### ISSUE THREAD

**Issue by dev-drprasad** [zupzup/golang-http-file-upload-download#9]
In article, it is mentioned that `const maxUploadSize = 2 * 1024 // 2 MB`. But actually right value for 2MB is `2 * 1024 * 1024`

Also minor typo: there are two variables `filetype` and `fileType`

You know, there are people like me who copy/paste code without reading whole article and directly deploy to prod without testing :)

**Comment by zupzup** [comment]
Hey, thanks for the heads-up! It seems I changed the code and not the article :see_no_evil: 

I updated the article at https://zupzup.org/go-http-file-upload-download/

thanks!
